[project]
name = "alch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.2.0",
]

[dependency-groups]
lint = [
    "ruff>=0.9.9",
]
test = [
    "pytest>=8.3.5",
]
